In [6]:
!pip install lxml

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting lxml
  Downloading lxml-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 5.6 MB/s eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-4.5.0

In [9]:

import requests
import lxml.html as lh
import pandas as pd

In [10]:

url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [11]:
page = requests.get(url)


doc = lh.fromstring(page.content)


tr_elements = doc.xpath('//tr')

In [13]:
tr_elements = doc.xpath('//tr')


col=[]
i=0


for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print ('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Postal Code
"
2:"Borough
"
3:"Neighborhood
"

In [14]:
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 3, the //tr data is not from our table 
    if len(T)!=3:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [15]:
[len(C) for (title,C) in col]

[181, 181, 181]

In [16]:

Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [17]:
df.head()

  Postal Code\n           Borough\n               Neighborhood\n
0         M1A\n      Not assigned\n                           \n
1         M2A\n      Not assigned\n                           \n
2         M3A\n        North York\n                  Parkwoods\n
3         M4A\n        North York\n           Victoria Village\n
4         M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [18]:
df.columns = ['Borough', 'Neighbourhood','Postcode']

cols = df.columns.tolist()
cols

cols = cols[-1:] + cols[:-1]

df = df[cols]

df.head()

                      Postcode Borough       Neighbourhood
0                           \n   M1A\n      Not assigned\n
1                           \n   M2A\n      Not assigned\n
2                  Parkwoods\n   M3A\n        North York\n
3           Victoria Village\n   M4A\n        North York\n
4  Regent Park, Harbourfront\n   M5A\n  Downtown Toronto\n

In [19]:
df = df.replace('\n',' ', regex=True)
df.head()

                     Postcode Borough      Neighbourhood
0                                M1A       Not assigned
1                                M2A       Not assigned
2                  Parkwoods     M3A         North York
3           Victoria Village     M4A         North York
4  Regent Park, Harbourfront     M5A   Downtown Toronto

In [20]:

df.drop(df.index[df['Borough'] == 'Not assigned'], inplace = True)

# Reset the index and dropping the previous index
df = df.reset_index(drop=True)

df.head(10)

                                       Postcode Borough      Neighbourhood
0                                                  M1A       Not assigned
1                                                  M2A       Not assigned
2                                    Parkwoods     M3A         North York
3                             Victoria Village     M4A         North York
4                    Regent Park, Harbourfront     M5A   Downtown Toronto
5             Lawrence Manor, Lawrence Heights     M6A         North York
6  Queen's Park, Ontario Provincial Government     M7A   Downtown Toronto
7                                                  M8A       Not assigned
8                             Islington Avenue     M9A          Etobicoke
9                               Malvern, Rouge     M1B        Scarborough

In [21]:
df = df.groupby(['Postcode', 'Borough'])['Neighbourhood'].apply(','.join).reset_index()
df.columns = ['Postcode','Borough','Neighbourhood']
df.head(10)

  Postcode Borough           Neighbourhood
0                   Canadian postal codes
1             M1A            Not assigned
2             M1Y            Not assigned
3             M1Z            Not assigned
4             M2A            Not assigned
5             M2B            Not assigned
6             M2C            Not assigned
7             M2E            Not assigned
8             M2G            Not assigned
9             M2S            Not assigned

In [22]:

df['Neighbourhood'] = df['Neighbourhood'].str.strip()

In [23]:

df.loc[df['Neighbourhood'] == 'Not assigned', 'Neighbourhood'] = df['Borough']

In [25]:

df[df['Borough'] == 'Queen\'s Park']

Empty DataFrame
Columns: [Postcode, Borough, Neighbourhood]
Index: []

In [26]:
df.shape

(181, 3)